QLDoanTruong.Web/Areas/YouthUnionUniversity/Controllers/AwardController.cs
using System.Web.Mvc;
using QLDoanTruong.Model;
using QLDoanTruong.Service;
using QLDoanTruong.Common;
using System.Net;
using QLDoanTruong.Web.Common;
using System.Collections.Generic;

namespace QLDoanTruong.Web.Areas.YouthUnionUniversity.Controllers
{
    [AllowPermission(RoleID="VIEW_AWARD")]
    public class AwardController : Controller
    {
        private AwardLevelService awardLevelService = new AwardLevelService();
        private AwardService awardService = new AwardService();
        public AwardController()
        {
            ViewBag.BreadCrumb = new List<BreadcrumbLink>()
            {
                new BreadcrumbLink(){Link="/Home/Dashboard/", Title = "Dashboard"},
            };
            //BREADCRUMB
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "/YouthUnionUniversity/Award/", Title = "Danh hiệu" });
        }

        //GET: /YouthUnionUniversity/Award/
        public ActionResult Index()
        {
            ViewBag.AwardLevelID = new SelectList(awardLevelService.GetAll(), "ID", "Name");
            ViewBag.Type = new SelectList(CommonList.ListUnionType, "ID", "Name");
            return View(awardService.GetAll());
        }

        [HttpPost, ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult SearchAward(int? type, int? awardLevelID)
        {
            ViewBag.AwardLevelID = new SelectList(awardLevelService.GetAll(), "ID", "Name", awardLevelID);
            ViewBag.Type = new SelectList(CommonList.ListUnionType, "ID", "Name", type);

            return View(awardService.GetByAwardLevelAndType(awardLevelID, type));

        }
        // GET: /YouthUnionUniversity/Award/Create
        public ActionResult Create()
        {
            ViewBag.AwardLevelID = new SelectList(awardLevelService.GetAll(), "ID", "Name");
            ViewBag.Type = new SelectList(CommonList.ListUnionType, "ID", "Name", ConstraintUnionType.MEMBER);
            //BREADCRUMB
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "", Title = "Thêm Danh hiệu" });
            return View();
        }

        // POST: /YouthUnionUniversity/Award/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Award award)
        {
            //BREADCRUMB
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "", Title = "Thêm Danh hiệu" });
            
            ViewBag.AwardLevelID = new SelectList(awardLevelService.GetAll(), "ID", "Name", award.AwardLevelID);
            ViewBag.Type = new SelectList(CommonList.ListUnionType, "ID", "Name", award.Type);

            ViewBag.Success = false;
            if (ModelState.IsValid)
            {

                awardService.Add(award);
                ViewBag.Success = true;
                return View();
            }
          
            return View(award);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Award award = awardService.GetSingleById(id);

            if (award == null)
            {
                return HttpNotFound();
            }
            //BREADCRUMB
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "", Title = "Cập nhật Danh hiệu" });
            
            ViewBag.AwardLevelID = new SelectList(awardLevelService.GetAll(), "ID", "Name", award.AwardLevelID);
            ViewBag.Type = new SelectList(CommonList.ListUnionType, "ID", "Name", award.Type);

            return View(award);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Award award)
        {
            //BREADCRUMB
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "", Title = "Cập nhật Danh hiệu" });
           
            ViewBag.AwardLevelID = new SelectList(awardLevelService.GetAll(), "ID", "Name", award.AwardLevelID);
            ViewBag.Type = new SelectList(CommonList.ListUnionType, "ID", "Name", award.Type);
            ViewBag.Success = false;

            //Bổ sung ngày hoạt động
            if (ModelState.IsValid)
            {
                awardService.Update(award);
                ViewBag.Success = true;
                return View();
            }
            
            return View(award);
        }

        public bool Delete(long? id)
        {
            if (id == null)
            {
                return false;
            }
            var award = awardService.GetSingleById(id);
            if (award == null)
            {
                return false;
            }
            try
            {
                awardService.Delete(award);
                return true;
            }
            catch
            {
                return false;
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                awardService.Dispose();
                awardLevelService.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

QLDoanTruong.Web/Areas/YouthUnionUniversity/Controllers/AwardLevelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLDoanTruong.Model;
using QLDoanTruong.Service;
using QLDoanTruong.Web.Common;
using QLDoanTruong.Common;

namespace QLDoanTruong.Web.Areas.YouthUnionUniversity
{
    [AllowPermission(RoleID = "VIEW_AWARD")]
    public class AwardLevelController : Controller
    {
        private AwardLevelService awardLevelService = new AwardLevelService();

        public AwardLevelController()
        {
            ViewBag.BreadCrumb = new List<BreadcrumbLink>()
            {
                new BreadcrumbLink(){Link="/Home/Dashboard/", Title = "Dashboard"},
            };
            //BREADCRUMB
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "/YouthUnionUniversity/AwardLevel/", Title = "Cấp bậc khen thưởng" });
        }
        //
        // GET: /YouthUnionUniversity/AwardLevel/
        public ActionResult Index(bool?update=null)
        {
            
            if (update != null)
            {
                ViewBag.Success = update;
            }
            return View("Index", awardLevelService.GetAll());
        
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(AwardLevel level)
        {
            ViewBag.Success = false;
            try
            {
                if (level.ID == 0)
                    awardLevelService.Add(level);
                else
                    awardLevelService.Update(level);
                ViewBag.Success = true;
            }
            catch { }
            return RedirectToAction("Index", new { update = ViewBag.Success });

        }

        [HttpPost]
        public bool Delete(int? id)
        {
            if (id == null) return false;
            var level = awardLevelService.GetSingleById(id);
            if (level == null) return false;
            try
            {
                awardLevelService.Delete(level);
                return true;
            }
            catch { }
            return false;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                awardLevelService.Dispose();
            }
            base.Dispose(disposing);
        }


	}
}

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/AwardLevel/Index.cshtml
@model IEnumerable<QLDoanTruong.Model.AwardLevel>

@{
    ViewBag.Title = "Cấp bậc khen thưởng";
}

@section scripts{
    <script type="text/javascript">
        $(function () {
                @if (ViewBag.Success != null)
                {
        @Html.Raw(ViewBag.Success ? "notifySuccess('Thao tác thành công!');" : "notifyError('Đã có lỗi! Bạn vui lòng kiểm tra lại thông tin đã nhập!');");

                }

            $('table#tblAwardLevel').on('click', "a.btn-delete", function (e) {

                var tr = $('tr', 'table#tblAwardLevel').get($(this).closest('tr').index());
                confirmDelete('@Url.Action("Delete")', { id: $(this).data('id') },
                    function () { $(tr).remove(); });
                e.preventDefault();
            });

            $('#divAwardLevel').on('click', 'a.btn-edit', function (e) {

                $('.modal-title').text('Cập nhật cấp danh hiệu');
                $('input[name="ID"]').val($(this).data('id'));
                $('input[name="Name"]').val($(this).closest('tr').find('td:eq(1)').text());

                //                e.preventDefault();
            });
            $('#divAwardLevel').on('click', '#btn-add', function (e) {

                $('.modal-title').text('Thêm cấp danh hiệu');
                $('input[name="ID"]').val('');
                $('input[name="Name"]').val('');

                //                e.preventDefault();
            });
        });
    </script>
}

<ul class="nav nav-tabs">
    <li><a href="@Url.Action("Index","Award")">Danh hiệu</a></li>
    <li class="active"><a href="#">Cấp khen thưởng</a></li>
</ul>
<br />


<div class="pull-right">
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-primary" id="btn-add" data-toggle="modal" data-target="#modalAdd">
        <i class="fa fa-plus"></i> Thêm cấp bậc
    </button>


    <!-- Modal -->
    <div id="modalAdd" class="modal fade" role="dialog">
        @using (Html.BeginForm("Update", "AwardLevel", FormMethod.Post))
        {
        @Html.AntiForgeryToken()
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Thêm cấp khen thưởng</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-md-4">Tên cấp khen thưởng</label>
                            <div class="col-md-7">
                                <input type="hidden" name="ID" />
                                <input type="text" required class="form-control" name="Name" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="btn-ok" class="btn btn-success">OK</button>
                    <button type="button" class="btn btn-default" id="btn-cancel" data-dismiss="modal">Hủy bỏ</button>

                </div>
            </div>

        </div>
        }
    </div>

</div>

<br />

<br />

<div id="divAwardLevel">
    <table id="tblAwardLevel" class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Tên cấp bậc danh hiệu</th>
            <th>Thao tác</th>
        </tr>
        @{var stt = 1;}
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center">@(stt++)</td>
                <td>@Html.DisplayFor(m => item.Name)</td>
                <td class="text-center">
                    <a href="#" class="btn fa fa-pencil btn-edit" data-toggle="modal" data-id="@item.ID" data-target="#modalAdd"></a>
                    <a href="#" title="Xoá" data-id=@item.ID class="btn fa fa-trash btn-delete" style="color:red"></a>
                </td>
            </tr>
        }
    </table>
</div>