QLDoanTruong.Web/Areas/YouthUnionUniversity/Controllers/WorkScheduleController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using QLDoanTruong.Model.ViewModel;
using QLDoanTruong.Model;
using QLDoanTruong.Service;
using QLDoanTruong.Common;
using System.Net;
using System;
using System.Threading.Tasks;
using System.IO;
using QLDoanTruong.Web.Common;
using PagedList;

namespace QLDoanTruong.Web.Areas.YouthUnionUniversity.Controllers
{
    //[Permission(RoleID = "UNIVERSITY")]
    [AllowUser]
    public class WorkScheduleController : Controller
    {
        private WorkScheduleService scheduleService = new WorkScheduleService();
        private WorkScheduleDetailService detailScheduleService = new WorkScheduleDetailService();

        public WorkScheduleController()
            : base()
        {
            ViewBag.BreadCrumb = new List<BreadcrumbLink>()
            {
                new BreadcrumbLink(){Link="/Home/Dashboard/", Title = "Dashboard"},
            };
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "/YouthUnionUniversity/WorkSchedule/", Title = "Lịch tuần" });
        }
        //
        // GET: /YouthUnionUniversity/WorkSchedule/
        [AllowPermission(RoleID = "VIEW_SCHEDULE")]
        public ActionResult Index()
        {
            using (var schoolYearService = new SchoolYearService())
            {
                var currentSchoolYear = schoolYearService.GetCurrent();
                if (currentSchoolYear == null)
                {
                    ViewBag.ErrorMessage = "Chưa thiết lập năm học hiện tại";
                    return View();
                }
                ViewBag.SchoolYear = currentSchoolYear.Name;
                //Tìm tuần cuối cùng đã có lịch
                //int lastWeek = scheduleService.GetLastWeekHasSchedule(currentSchoolYear.ID);
                //số tuần của năm học
                int weekAmount = (int)(currentSchoolYear.EndDate - currentSchoolYear.StartDate).TotalDays / 7;
                List<SelectListItem> weeks = new List<SelectListItem>();
                for (int week = 1; week <= weekAmount; week++)
                {
                    var startDate = currentSchoolYear.StartDate.AddDays(week * 7);
                    var endDate = startDate.AddDays(6);
                    weeks.Add(new SelectListItem()
                    {
                        Value = (week + 1).ToString(),
                        Text = string.Format("Tuần {0} - Từ {1:dd/MM/yyyy} đến {2:dd/MM/yyyy}", week + 1, startDate, endDate)
                    });
                }
                ViewBag.Week = new SelectList(weeks, "Value", "Text");
            }
            ///Xem có quyền sử không
            ViewBag.EditSchedule = new UserService()
                        .GetPermissionByUsername(System.Web.HttpContext.
                                Current.Session["Username"].ToString()).Contains("MANAGE_SCHEDULE");

            return View();

        }

        public PartialViewResult GetWorkSchedules(int? page)
        {

            int pageSize = 12;
            int pageNumber = (page ?? 1);
            //lấy quyền để trên giao diện
            ViewBag.EditSchedule = new UserService()
                        .GetPermissionByUsername(System.Web.HttpContext.
                                Current.Session["Username"].ToString()).Contains("MANAGE_SCHEDULE");

            return PartialView("_WorkSchedulesListPartial", scheduleService.GetAll().ToPagedList(pageNumber, pageSize));
        }



        //[HttpPost]
        //[ValidateInput(false)]
        //public FileResult Export(string html)
        //{
        //    //string fil HttpContext.Server.MapPath("~/Uploads/" + "avc.pdf"));
        //    var bytes = CommonUtility.PdfSharpConvert(html);
        //    MemoryStream workStream = new MemoryStream();
        //    workStream.Write(bytes, 0, bytes.Length);
        //    workStream.UnionPosition = 0;  

        //    return File(workStream, "application/pdf", "avc.pdf");  


        //}

        [AllowPermission(RoleID = "MANAGE_SCHEDULE")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int week)
        {
            var currentSchoolYear = new SchoolYearService().GetCurrent();
            var startDate = currentSchoolYear.StartDate.AddDays((week - 1) * 7);
            var endDate = startDate.AddDays(6);
            //KIỂM TRA ĐÃ tồn tại
            var workSchedule = scheduleService.GetByWeek(week, currentSchoolYear.ID);
            if (workSchedule == null)
            {
                workSchedule = scheduleService.Add(new WorkSchedule()
                {
                    Name = string.Format("Lịch công tác tuần {0} năm học {1} (Từ {2:dd/MM/yyyy} đến {3:dd/MM/yyyy})", week, currentSchoolYear.Name, startDate, endDate),
                    UnitID = 1,//tạm thời của đoàn trường
                    SchoolYearID = currentSchoolYear.ID,
                    StartDate = startDate,
                    Week = week
                });
                return RedirectToAction("CreateDetail", new { workSchedule.ID });
            }
            return RedirectToAction("Details", new { id = workSchedule.ID });
        }

        //public ActionResult Details(long? facultyID)
        //{
        //    if (facultyID == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    var faculty = scheduleService.GetSingleById(facultyID);
        //    if (faculty == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ScheduleName = faculty.FunctionName;
        //    ViewBag.ScheduleID = facultyID;
        //    var normalSchedule = detailScheduleService.GetAllViewByShedule(facultyID);
        //    var everydaySchedule = detailScheduleService.GetEveryDay(facultyID);
        //    return View(new Tuple<List<WorkScheduleDetailViewModel>, List<WorkScheduleDetail>>(normalSchedule, everydaySchedule));

        //}
        [AllowPermission(RoleID = "VIEW_SCHEDULE")]
        public ActionResult Details(long? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var workSchedule = scheduleService.GetSingleById(id);
            if (workSchedule == null)
            {
                return HttpNotFound();
            }
            ViewBag.EditSchedule = new UserService()
                        .GetPermissionByUsername(System.Web.HttpContext.
                                Current.Session["Username"].ToString()).Contains("MANAGE_SCHEDULE");

            ViewBag.ScheduleName = workSchedule.Name;
            ViewBag.ScheduleID = id;
            var normalSchedule = detailScheduleService.GetDisplayBySchedule(id).OrderBy(x => x.Date).ToList();
            var everydaySchedule = detailScheduleService.GetEveryDay(id);
            //breadcrumb
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "", Title = workSchedule.Name });
        
            return View(new Tuple<List<WorkScheduleDisplayViewModel>, List<WorkScheduleDetail>>(normalSchedule, everydaySchedule));
        }

        [AllowPermission(RoleID = "MANAGE_SCHEDULE")]
        public ActionResult CreateDetail(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var workSchedule = scheduleService.GetSingleById(id);
            if (workSchedule == null)
            {
                return HttpNotFound();
            }
            ViewBag.ScheduleID = id;
            ViewBag.ScheduleName = workSchedule.Name;
            //Tải Ngày trong tuần
            List<SelectListItem> dayOfWeekList = new List<SelectListItem>();
            for (int i = 0; i < 7; i++)
            {
                var date = workSchedule.StartDate.AddDays(i);
                dayOfWeekList.Add(new SelectListItem()
                {
                    Value = date.ToShortDateString(),
                    Text = DateUtility.GetDayOfWeekVietnamese(date) + " - " + date.ToString("dd/MM/yyyy")

                });
            }
            ViewBag.Date = new SelectList(dayOfWeekList, "Value", "Text");
            //tải đơn vị
            ViewBag.Unit = new UnitService().GetAll().Select(x => new SelectListItem
                                                            {
                                                                Value = "1::" + x.ID,
                                                                Text = x.Name
                                                            }).ToList();
            //tải lảnh đạo
            ViewBag.Leader = new LeaderUnitService().GetAllView().Select(x => new SelectListItem
                                    {
                                        Value = "2::" + x.MemberID,
                                        Text = string.Format("{0} {1} - {2} - {3}", x.Lastname, x.Firstname, x.Position, x.UnitName)
                                    }).ToList();
            //breadcrumb
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "/YouthUnionUniversity/WorkSchedule/Details/"+id, Title = workSchedule.Name });
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "" + id, Title = "Thêm lịch" });
        
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult CreateNormalDetail(WorkScheduleDetailViewModel scheduleDetailView)
        {
            var detail = detailScheduleService.Add(scheduleDetailView);
            return RedirectToAction("Details", new { id = scheduleDetailView.WorkScheduleID });

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult CreateEveryDayDetail(string content, int workScheduleId)
        {
            var detail = new WorkScheduleDetail()
            {

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/WorkSchedule/CreateDetail.cshtml
@model QLDoanTruong.Model.ViewModel.WorkScheduleDetailViewModel

@{
    ViewBag.Title = "Thêm chi tiết " + ViewBag.ScheduleName;
}

@section styles
{
    <link href="~/Assets/addition/css/timepicker.min.css" rel="stylesheet" />
    <style>
        .checklistbox {
            height: 110px;
            overflow: auto;
            border: 1px solid #d4dbe0;
            padding-left: 20px;
            width: 100%;
        }
    </style>
}

@section scripts
{
    <!--Time picker-->
    <script src="~/Assets/addition/js/timepicker.min.js"></script>

    <!--CKEditor-->
    <script src="~/Assets/ckeditor/ckeditor.js"></script>

    <script>
        $(document).ready(function () {
            //load CKEditor
            CKEDITOR.replace("content1");
            CKEDITOR.replace("content2");
            CKEDITOR.replace("content3");
            CKEDITOR.config.height = 100;
            //load timepicker
            $('.timepicker').timepicker({
                timeFormat: 'H:mm',
                interval: 30,
                minTime: '4:00',
                maxTime: '23:00',
                defaultTime: '7:00',
                startTime: '6:00',
                //                dynamic: true,
                dropdown: true,
                scrollbar: true
            });
        });

    </script>
}
<div class="tab-control">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#tabs-1">Lịch hàng ngày</a></li>
        <li><a data-toggle="tab" href="#tabs-2">Cả tuần</a></li>
        <li><a data-toggle="tab" href="#tabs-3">Ngày kỷ niệm</a></li>
    </ul>
    <div class="tab-content">

        <!--Tab hằng ngày-->
        <div id="tabs-1" class="tab-pane fade in active">
            @using (Html.BeginForm("CreateNormalDetail", "WorkSchedule"))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <input type="hidden" value="@ViewBag.ScheduleID" name="WorkScheduleID" />
                    <div class="form-group">
                        <label class="control-label col-md-2"> Ngày</label>
                        <div class="col-md-10">
                            @Html.DropDownList("Date", null, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2"> Thời gian</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Time, new { @class = "form-control timepicker" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2"> Chủ trì</label>
                        <div class="col-md-10">
                            <h5>Ban chấp hành:</h5>
                            <div class="checklistbox">
                                @foreach (var item in ViewBag.Unit)
                                {
                                <div class="checkbox">
                                    <label>
                                        <input name="Chairman" type="checkbox" value="@item.Value" /> @item.Text
                                    </label>

                                </div>
                                }
                            </div>

                            <h5>Cá nhân:</h5>
                            <div class="checklistbox">
                                @foreach (var item in ViewBag.Leader)
                                {
                                <div class="checkbox">
                                    <label>
                                        <input name="Chairman" type="checkbox" value="@item.Value" />
                                        @item.Text
                                    </label>

                                </div>
                                }
                            </div>
                            <h5>Khác: </h5>
                            @Html.TextAreaFor(m => m.ChairManOther, new { @class = "form-control", @row = 5 })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2"> Nội dung</label>
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @id = "content1" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2"> Thành phần tham dự</label>
                        <div class="col-md-10">
                            <h5>Ban chấp hành:</h5>
                            <div class="checklistbox">
                                @foreach (var item in ViewBag.Unit)
                                {
                                <div class="checkbox">
                                    <label>
                                        <input name="Participants" type="checkbox" value="@item.Value" /> @item.Text
                                    </label>

                                </div>
                                }
                            </div>

                            <h5>Cá nhân:</h5>
                            <div class="checklistbox">
                                @foreach (var item in ViewBag.Leader)
                                {
                                <div class="checkbox">
                                    <label>
                                        <input name="Participants" type="checkbox" value="@item.Value" />
                                        @item.Text
                                    </label>

                                </div>
                                }
                            </div>
                            <h5>Khác: </h5>
                            @Html.TextAreaFor(m => m.ParticipantOther, new { @class = "form-control", @row = 5 })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2"> Địa điểm</label>
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Location, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-offset-2">
                        <label class="text-danger">
                            @Html.EditorFor(x => x.IsImportant) Là sự kiện quan trọng
                        </label>
                    </div>
                    <div class="col-md-offset-2">
                        <input type="submit" value="Thêm" class="btn btn-primary" />
                    </div>
                </div>
            }

        </div>
        <!--End tab hăng ngày-->
        <!--Tab Cả tuần-->
        <div id="tabs-2" class="tab-pane fade">
            @using (Html.BeginForm("CreateEveryDayDetail", "WorkSchedule"))
            {
                @Html.AntiForgeryToken();
                <div class="form-horizontal">
                    <input type="hidden" value="@ViewBag.ScheduleID" name="WorkScheduleID" />

                    <div class="form-group">
                        <label class="control-label col-md-2"> Nội dung</label>
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @id = "content2" })
                        </div>
                    </div>

                    <div class="col-md-offset-2">
                        <input type="submit" value="Thêm" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
        <!--End tab cả tuần-->
        <!--Tab kỷ niệm-->
        <div id="tabs-3" class="tab-pane fade">
            @using (Html.BeginForm("CreateUniversaryDetail", "WorkSchedule"))
            {
                @Html.AntiForgeryToken();
                <div class="form-horizontal">
                    <input type="hidden" value="@ViewBag.ScheduleID" name="WorkScheduleID" />
                    <div class="form-group">
                        <label class="control-label col-md-2"> Ngày</label>
                        <div class="col-md-10">
                            @Html.DropDownList("Date", null, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2"> Nội dung</label>
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @id = "content3" })
                        </div>
                    </div>
                    <div class="col-md-offset-2">
                        <input type="submit" value="Thêm" class="btn btn-primary" />
                    </div>
                </div>
            }
        </div>
        <!--End tab kỷ niệm-->
    </div>
</div>

<div>
    @Html.ActionLink("Trở về", "Details", new { scheduleID = ViewBag.ScheduleID })
</div>

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/WorkSchedule/Details.cshtml
@model Tuple<List<QLDoanTruong.Model.ViewModel.WorkScheduleDisplayViewModel>, List<QLDoanTruong.Model.WorkScheduleDetail>>

@{
    ViewBag.Title = ViewBag.ScheduleName;
}

@section styles{
    <style>
        .important-event {
            color: green;
            font-weight: bold;
        }
    </style>
}

@section scripts{
    <script type="text/javascript">
        $(function () { 
        $("#export").click(function (e) {
            e.preventDefault();
            $('form').append($("<input></input>").attr('type', 'area').attr('name', 'html').attr('value', $('#schedule').html()));
            //$('form').submit();

        });
        $('table').on('click', "a.btn-delete", function (e) {

            var tr = $('tr', 'table').get($(this).closest('tr').index());
            confirmDelete('@Url.Action("DeleteDetail")', { id: $(this).data('id') },
                function () { $(tr).remove(); });
            e.preventDefault();
        });
        });
    </script>
}
<!--Thêm lich cho tuần mới-->
@if (ViewBag.EditSchedule)
{
    <div class="pull-right box-tool">
        <a href="@Url.Action("CreateDetail", new { id = ViewBag.ScheduleID })" class="btn btn-primary">
            <i class="fa fa-plus"></i> Thêm lịch
        </a>
        
        <!--export-->
        @*<form method="post" action="@Url.Action("Export")">
                <button type="submit" class="btn btn-default" id="export">Xuất Excel</button>
            </form>*@
        <!--end export-->

    </div>
}
<!--End thêm lịch-->
<div id="schedule">
    <table class="table table-bordered">
        <tr>
            <th>
                Thời gian
            </th>
            <th>
                Chủ trì
            </th>
            <th>
                Nội dung
            </th>
            <th>
                Thành phần tham dự
            </th>
            <th>
                Địa điểm
            </th>
            @if (ViewBag.EditSchedule)
            {

                <th></th>
            }
        </tr>
        @foreach (var item in Model.Item1)
        {
            <tr>
                <td colspan="6">
                    <b>
                        @Html.DisplayFor(modelItem => item.DayOfWeek)
                        -
                        @Html.DisplayFor(modelItem => item.Date)

                    </b>
                </td>
            </tr>
            foreach (var detail in item.Details)
            {
                <tr @(detail.IsImportant ? "class=important-event" : "")>
                    @if (detail.IsDayLong)
                    {
                        <td colspan="5" class="text-danger h5" align="center">
                            @Html.Raw(detail.Content)
                        </td>
                    }
                    else
                    {
                        <td>
                            @*     @Html.DisplayFor(modelItem => detail.Time)*@
                            @detail.Time
                        </td>
                        <td>
                            @foreach (var chairman in detail.Chairman)
                            {
                                <p>- @chairman</p>
                            }
                        </td>
                        <td>
                            @Html.Raw(detail.Content)
                        </td>
                        <td>
                            @foreach (var participant in detail.Participants)
                            {
                                <p>- @participant</p>
                            }
                        </td>
                        <td>
                            @detail.Location
                        </td>
                    }
                    @if (ViewBag.EditSchedule)
                    {

                        <td class="text-center">
                            <a href="#"  title="Xoá" data-id=@detail.ID class="btn fa fa-trash btn-delete" style="color:red"></a>
    @*@Html.ActionLink(" ", "DeleteDetail", new { id = detail.ID }, new { @class = "btn fa fa-trash" })*@
                        </td>
                    }
                </tr>
            }


        }
        @for (int i = 0; i < Model.Item2.Count; i++)
        {
            <tr>
                @if (i == 0)
                {
                    <td rowspan="@Model.Item2.Count"><b>Cả tuần</b></td>
                }
                <td colspan="4">@Html.Raw(Model.Item2[i].Content)</td>
                @if (ViewBag.EditSchedule)
                {
                    <td class="text-center">
                        <a href="#" title="Xoá" data-id=@Model.Item2[i].ID class="btn fa fa-trash btn-delete" style="color:red"></a>

                        @*@Html.ActionLink(" ", "DeleteDetail", new { id = Model.Item2[i].ID }, new { @class = "btn btn-delete fa fa-trash" })*@
                    </td>
                }
            </tr>
        }


    </table>
</div>

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/WorkSchedule/Index.cshtml
@{
    ViewBag.Title = "Lịch làm việc";
}

@section scripts{
    <script>
        $(function () {
            $('#divSchedule').on('click', "a.btn-delete", function (e) {

                var tr = $('tr', 'table').get($(this).closest('tr').index());
                confirmDelete('@Url.Action("Delete")', { id: $(this).data('id') },
                    function () { $(tr).remove(); });
                e.preventDefault();
            });
        });
    </script>
}
@if (ViewBag.ErrorMessage != null)
{
    <h3 class="error-message">@ViewBag.ErrorMessage</h3>
}
else
{
    if (ViewBag.EditSchedule)
    {
    <!--Thêm lich cho tuần mới-->
        <div class="pull-right box-tool">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                <i class="fa fa-calendar-plus-o"></i>
                Thêm lịch tuần
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <form class="form-horizontal" action="@Url.Action("Create")" method="post">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h5 class="modal-title" id="exampleModalLabel">Thêm lịch tuần mới cho năm học @ViewBag.SchoolYear</h5>

                            </div>
                            <div class="modal-body">

                                @Html.AntiForgeryToken()
                                <div class="form-group">
                                    <label class="control-label col-md-3">Tuần:</label>
                                    <div class="col-md-8">
                                        @Html.DropDownList("Week", null, new { @class = "form-control" })
                                    </div>
                                </div>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                <button type="submit" class="btn btn-primary">OK</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    <!--End thêm lịch-->

    }

    <div id="divSchedule">
        @{Html.RenderAction("GetWorkSchedules");}
    </div>
}

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/WorkSchedule/_WorkSchedulesListPartial.cshtml
@model PagedList.IPagedList<QLDoanTruong.Model.WorkSchedule>
@using PagedList.Mvc

<table class="table table-bordered">
    <tr>
        <th style="width:20px">#</th>

        <th>
            Lịch tuần
        </th>
        <th>
            Cập nhật
        </th>
        @if (ViewBag.EditSchedule)
        {
            <th>Thao tác</th>
        }
    </tr>
    @{var stt = 1;}
    @foreach (var item in Model)
    {
        <tr>
            <td>@(stt++)</td>
            <td>
                <a href="/YouthUnionUniversity/WorkSchedule/Details/@item.ID">
                    @Html.DisplayFor(modelItem => item.Name)
                </a>
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.ModifiedDate)
            </td>
            @if (ViewBag.EditSchedule)
            {
                <td class="text-center">
                    <a href="#" title="Xoá" data-id=@item.ID class="btn fa fa-trash btn-delete" style="color:red"></a>
                    @*<a href="#" title="Xoá" data-id=@item.ID class="btn fa fa-trash btn-delete" style="color:red"></a>*@
                </td>
            }
        </tr>
    }

</table>

@if (Model.PageCount > 1)
{
    @Html.PagedListPager(Model, Page => Url.Action("GetWorkSchedules", new { Page }),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                                new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "divSchedule" }))
}