QLDoanTruong.Web/Areas/YouthUnionUniversity/Controllers/AchievementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using QLDoanTruong.Common;
using System.Web.Mvc;
using QLDoanTruong.Model;
using QLDoanTruong.Service;
using QLDoanTruong.Common;
using QLDoanTruong.Model.ViewModel;
using System.IO;
using QLDoanTruong.Web.Common;

namespace QLDoanTruong.Web.Areas.YouthUnionUniversity.Controllers
{
     [AllowUser]
    public class AchievementController : Controller
    {
        private AchievementService achievementService = new AchievementService();
        private AwardService awardService = new AwardService();
        private YouthUnionMemberService memberService = new YouthUnionMemberService();
        private AwardLevelService awardLevelService = new AwardLevelService();
        private SchoolYearService schoolYearService = new SchoolYearService();

        public AchievementController()
        {
            ViewBag.BreadCrumb = new List<BreadcrumbLink>()
            {
                new BreadcrumbLink(){Link="/Home/Dashboard/", Title = "Dashboard"},
            };
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "/YouthUnionUniversity/Achievement/", Title = "Khen thưởng" });
        }

        //GET: /YouthUnionUniversity/Achievement/
        public ActionResult Index()
        {
            ViewBag.AwardLevelID = new SelectList(awardLevelService.GetAll(), "ID", "Name");
            ViewBag.AwardID = new SelectList(awardService.GetAll(), "ID", "Name");
            ViewBag.SchoolYearID = new SelectList(schoolYearService.GetAll(), "ID", "Name");

            return View(achievementService.GetAllView());
        }

        [HttpPost, ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult SearchAchievement(int? awardID, int? awardLevelID, int? schoolYearID)
        {
            ViewBag.AwardLevelID = new SelectList(awardLevelService.GetAll(), "ID", "Name", awardLevelID);

            ViewBag.AwardID = new SelectList(awardService.GetByAwardLevel(awardLevelID), "ID", "Name", awardID);
            ViewBag.SchoolYearID = new SelectList(schoolYearService.GetAll(), "ID", "Name", schoolYearID);

            return View(achievementService.GetViewByAward(awardLevelID, awardID, schoolYearID));

        }
        //[HttpPost]
        //public JsonResult GetAward(int? awardLevelID)
        //{
        //    return Json(awardService.GetByAwardLevel(awardLevelID).Select(x => new { x.ID, x.FunctionName }), JsonRequestBehavior.AllowGet);
        //}


        //// GET: /YouthUnionUniversity/Achievement/Details/5
        //public ActionResult Details(int? facultyID)
        //{
        //    if (facultyID == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    var achievement = achievementService.GetSingleViewByID(facultyID);
        //    if (achievement == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(achievement);
        //}

        // GET: /YouthUnionUniversity/Achievement/Create
        public ActionResult Create()
        {
            //BreadCrumb
            
            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "/YouthUnionUniversity/Achievement/Create", Title = "Thêm khen thưởng" });

            ViewBag.AwardLevelID = new SelectList(awardLevelService.GetAll(), "ID", "Name");
            ViewBag.SchoolYearID = new SelectList(schoolYearService.GetAll(), "ID", "Name");

            return View();
        }

        [HttpPost]
        public JsonResult GetAwards(int awardLevelID)
        {
            var result = awardService.GetByAwardLevel(awardLevelID).Select(x => new { x.ID, x.Name });
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public PartialViewResult GetResultImport(HttpPostedFileBase file, int schoolYearID, int awardID)
        {
            if (file == null) return null;

            string path = HttpContext.Server.MapPath("~/Uploads/Imports/") + file.FileName;
            file.SaveAs(path);
            var fileInfo = new FileInfo(path);
            var members = new List<ImportAchievementStudentViewModel>();

            var typeUnion = awardService.GetSingleById(awardID).Type;

            //Đọc file excel
            NPOI.HSSF.UserModel.HSSFWorkbook hssfwb = null;//xls
            NPOI.XSSF.UserModel.XSSFWorkbook xssfwb = null;//xlsx

            using (FileStream fileStream = new FileStream(path, FileMode.Open, FileAccess.Read))
            {
                if (fileInfo.Extension == ".xls")
                    hssfwb = new NPOI.HSSF.UserModel.HSSFWorkbook(fileStream);
                else
                    xssfwb = new NPOI.XSSF.UserModel.XSSFWorkbook(fileStream);
            }
            NPOI.SS.UserModel.ISheet sheet = null;
            if (hssfwb != null)
                sheet = hssfwb.GetSheetAt(0);
            else
                sheet = xssfwb.GetSheetAt(0);
            if (typeUnion == ConstraintUnionType.MEMBER)
            {

                for (int row = 3; row <= sheet.LastRowNum; row++)
                {
                    var item = new ImportAchievementStudentViewModel()
                    {
                        StudentCode = sheet.GetRow(row).GetCell(1).StringCellValue,
                        LastName = sheet.GetRow(row).GetCell(3).StringCellValue,
                        FirstName = sheet.GetRow(row).GetCell(5).StringCellValue,
                    };
                    //Xử lý và chen vào CSDL nếu hợp lệ
                    if (item.StudentCode == string.Empty || item.FirstName == string.Empty
                      || item.LastName == string.Empty)
                    {
                        item.Result = "Lỗi: Thiếu thông tin cá nhân";

                    }
                    else if (!memberService.ExistedMemberCode(item.StudentCode))
                    {
                        item.Result = "Lỗi: Mã SV/CB Không tồn tại trong hệ thống!";
                    }
                    else
                    {
                        var mem = memberService.GetSingleByMemberCode(item.StudentCode);
                        var htMem = StringUtility.RemoveRedundancySpace(mem.Lastname + " " + mem.Firstname);
                        var htImport = StringUtility.RemoveRedundancySpace(item.LastName + " " + item.FirstName);
                        if (!string.Equals(htMem, htImport, StringComparison.CurrentCultureIgnoreCase))
                        {
                            item.Result = "Lỗi: Sai thông tin họ tên";
                        }
                        else
                        {
                            try
                            {
                                achievementService.Add(new Achievement()
                                {
                                    Type = typeUnion,
                                    AwardID = awardID,
                                    SchoolYearID = schoolYearID,
                                    YouthUnionID = mem.ID
                                });
                                item.Result = "Thành công!";
                            }
                            catch
                            {
                                item.Result = "Lỗi hệ thống!";
                            }
                        }
                    }

                    members.Add(item);
                }
            }


            fileInfo.Delete();

            return PartialView("_ImportAchievementPartial", members.OrderBy(x => x.Result));
        }


        public bool Delete(long? id)
        {
            if (id == null)
            {
                return false;
            }
            var achievement = achievementService.GetSingleById(id);
            if (achievement == null)
            {
                return false;
            }
            try
            {
                achievementService.Delete(achievement);
                return true;
            }
            catch
            {
                return false;
            }
        }


        //// POST: /YouthUnionUniversity/Achievement/Create

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,AchievementCode,Content,Score,FunctionName,UnitID,YouthUnionMemberStaffID")]Achievement achievement, string dateRange, HttpPostedFileBase fileStream)
        //{
        //    //Bổ sung ngày hoạt động
        //    var range = DateUtility.GetDateRange(dateRange);
        //    achievement.StartDate = range.StartDate;
        //    achievement.EndDate = range.EndDate;

        //    //không cho cán bộ phụ trách null
        //    if (achievement.YouthUnionMemberStaffID == 0)
        //        ModelState.AddModelError("YouthUnionMemberStaffID", "Cán bộ phụ trách không thể để trống");
        //    if (ModelState.IsValid)
        //    {

        //        if (fileStream != null)
        //        {
        //            var path = HttpContext.Server.MapPath(ConstraintName.DOCUMENT_ACTIVITY_DIRECTORY_PATH) + fileStream.FileName;
        //            fileStream.SaveAs(path);
        //            achievement.Document = fileStream.FileName;
        //        }

        //        achievementService.Add(achievement);
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.StartDate = achievement.StartDate.ToString("dd/MM/yyyy");
        //    ViewBag.EndDate = achievement.EndDate.ToString("dd/MM/yyyy");

        //    ViewBag.UnitID = new SelectList(new UnitService().GetAll(), "ID", "FunctionName", achievement.UnitID);
        //    ViewBag.YouthUnionMemberStaffID = new SelectList(new LeaderService().GetAllViewByUnitID(achievement.UnitID)
        //                                            .Select(x => new
        //                                            {
        //                                                ID = x.MemberID,

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/Achievement/Create.cshtml
@{
    ViewBag.Title = "Thêm Khen thưởng";
}

@section scripts{
    <script src="~/Assets/addition/js/my-upload.js"></script>

    <script type="text/javascript">
        //function onLoading() {
        //    $('#btn-import i').show();
        //    $('#btn-import').attr("disabled", true);
        //}
        //function endLoading() {
        //    $('#btn-import i').hide();
        //    $('#btn-import').attr("disabled", false);
        //}
        window.addEventListener("submit", function (e) {
            var error = getErrorUploadFile('input[name="file"]');
            if (error != '') {
                notifyError(error);
                return;
            }
            //console.log($()[0].files[0].name); return;
            notifyLoading("Đang xử lý...");


            var form = e.target;
            if (form.getAttribute("enctype") === "multipart/form-data") {
                if (form.dataset.ajax) {
                    e.preventDefault();
                    e.stopImmediatePropagation();
                    var xhr = new XMLHttpRequest();
                    xhr.open(form.method, form.action);
                    xhr.onreadystatechange = function () {
                        if (xhr.readyState == 4 && xhr.status == 200) {
                            if (form.dataset.ajaxUpdate) {
                                var updateTarget = document.querySelector(form.dataset.ajaxUpdate);
                                if (updateTarget) {
                                    updateTarget.innerHTML = xhr.responseText;
                                    notifySuccess('Đã xử lý xong!');
                                }
                            }
                        } else {
                            notifyError('Đã xảy ra lỗi!');
                        }
                    };
                    xhr.send(new FormData(form));
                }
            }
        }, true);

        $(function () {
            $('input[type="file"]').change(function () {
                var error = getErrorUploadFile('input[type="file"]');

                if (error != '') {

                    notifyError(error);

                    $(this).val('');

                }
                $('#txtFile').val($(this).val());
            });


            $('#AwardLevelID').change(function () {
                $('#AwardID').children('option').remove();

                $.post("@Url.Action("GetAwards")",
                    {
                        awardLevelID: $('#AwardLevelID').val(),

                    },
                    function (result) {
                        //console.log(result);
                        $.each(result, function (index, item) {
                            $('#AwardID').append($('<option>', {
                                value: item.ID,
                                text: item.Name
                            }));
                        });
                        $('#btn-import').attr("disabled", result.length == 0);
                    }, 'json');
            });
            $('#AwardLevelID').trigger("change");
        });
    </script>
}


@using (Ajax.BeginForm("GetResultImport", null,
    new AjaxOptions()
    {
        HttpMethod = "POST",
        UpdateTargetId = "divResult",
        InsertionMode = InsertionMode.Replace
    },
        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-inline">
        <div class="form-group">
            <label class="control-label">Cấp khen thưởng:</label> <br />
            @Html.DropDownList("AwardLevelID", null, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label class="control-label">Giải thưởng:</label><br />
            <select class="form-control" name="AwardID" id="AwardID"></select>
        </div>
        <div class="form-group">
            <label class="control-label">Năm học:</label><br />
            @Html.DropDownList("SchoolYearID", null, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label class="control-label">Chọn tệp:</label>
            <br />
            <div class="input-group" style="min-width: 426px;">
                <input name="txtFile" placeholder="Chọn tệp .xls, .xlsx" type="text" readonly="readonly" id="txtFile" class="form-control">
                <span class="group-span-filestyle input-group-btn">
                    <button id="btnBrowse" type="button" value="Chọn tệp" class="btn btn-primary" style="padding:6px 12px !important; border-radius: 0"
                            onclick="document.getElementById('fileUpload').click();">
                        <i class="fa fa-folder-open"></i>
                    </button>
                </span>

            </div>

            <input type="file" style="display:none" accept=".xls, .xlsx" name="file" id="fileUpload" />

        </div>
        <div class="form-group">
          <br />
              <button id="btn-import" class="btn btn-success" type="submit">
                @*<i style="display:none; margin-right:5px" class="fa fa-circle-o-notch fa-spin"></i>*@ Tải lên
            </button>
        </div>
    </div>
}

<div class="box-tool"></div>
<div id="divResult">
    <!--Barng trar ve o day-->

</div>


@*<div>
    @Html.ActionLink("Trở về", "Index")
</div>*@

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/Achievement/Index.cshtml
@model IEnumerable<QLDoanTruong.Model.ViewModel.AchievementViewModel>

@{
    ViewBag.Title = "Quản lý Khen thưởng";
}

@section styles
{

}

@section scripts
{
    <script>
        $(document).ready(function () {
            $('#SchoolYearID, #AwardID').change(function () {
                $('#frm-filter').submit();
            });
            //load award
            $('#AwardLevelID').change(function () {
                $('#AwardID').val(null).change();
                
            });
            $('table').on('click', "a.btn-delete", function (e) {

                var tr = $('tr', 'table').get($(this).closest('tr').index());
                confirmDelete('@Url.Action("Delete")', { id: $(this).data('id') },
                    function () { $(tr).remove(); });
                e.preventDefault();
            });
        });
    </script>
}

<div class="pull-right">
    <a class="btn btn-primary" href="@Url.Action("Create")"><i class="fa fa-plus"></i> Thêm Khen thưởng</a>
</div>
@using (Html.BeginForm("Index", "Achievement", FormMethod.Post, new { @class = "form-inline", @id = "frm-filter" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label class="control-label">Cấp khen thưởng:</label>
        @Html.DropDownList("AwardLevelID", null, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label class="control-label">Giải thưởng:</label>
        @Html.DropDownList("AwardID", null, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label class="control-label">Năm học:</label>
        @Html.DropDownList("SchoolYearID", null, new { @class = "form-control" })
    </div>
}
<br />
<table class="table table-bordered">
    <tr>
        <th style="width:20px">#</th>
        <th>
            Đối tượng nhận khen thưởng
        </th>
        <th>
            Giải thưởng
        </th>
        <th>
            Văn bản quyết định
        </th>
        <th>Năm học</th>
        <th ></th>
    </tr>
    @{var stt = 1;}
    @foreach (var item in Model)
    {
        <tr>
            <td>@(stt++)</td>
            <td>
                @Html.DisplayFor(modelItem => item.YouthUnionName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AwardName)
            </td>

            <td>
                @if (item.Document != null)
                {
                    @Html.RouteLink(item.Document, "Download", new { fileName = item.Document, type = QLDoanTruong.Common.ConstraintName.ACHIEVEMENT_FILE }, null)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SchoolYearName)
            </td>
            <td class="text-center" nowrap>
               @* @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @class = "btn fa fa-pencil", title="Sửa"})*@
                @*@Html.ActionLink(" ", "Details", new { id = item.ID }, new { @class = "fa fa-newspaper-o", title="Chi tiết", style = "color:green" })*@
                    @*@Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "btn fa fa-trash-o", style="color:red", title="Xóa" })*@
                <a href="#" title="Xoá" data-id=@item.ID class="btn fa fa-trash btn-delete" style="color:red"></a>
            </td>
        </tr>
    }

</table>

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/Achievement/_ImportAchievementPartial.cshtml
@model IEnumerable<QLDoanTruong.Model.ViewModel.ImportAchievementStudentViewModel>
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Mã sinh viên</th>

        <th>Họ</th>
        <th>Tên</th>
        <th>Kết quả</th>
    </tr>
    @{int stt = 1;}
    @foreach (var item in Model)
    {
        <tr>
            <td>@(stt++)</td>
            <td>@item.StudentCode</td>
            <td>@item.LastName</td>
            <td>@item.FirstName</td>
            <td>@item.Result</td>
        </tr>
    }
</table>