QLDoanTruong.Web/Areas/YouthUnionUniversity/Controllers/YouthUnionMemberController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using QLDoanTruong.Model;
using QLDoanTruong.Service;
using System.Linq;
using PagedList;
using QLDoanTruong.Common;
using System.Web;
using System;
using QLDoanTruong.Model.ViewModel;
using System.Net;
using System.IO;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using NPOI.SS.Util;
using QLDoanTruong.Web.Common;
using OfficeOpenXml;


namespace QLDoanTruong.Web.Areas.YouthUnionUniversity.Controllers
{

    public class YouthUnionMemberController : BaseController
    {

        private YouthUnionFacultyService facultyService = new YouthUnionFacultyService();

        private AcademicYearService academicYearService = new AcademicYearService();
        private YouthUnionClassService classService = new YouthUnionClassService();
        private YouthUnionMemberService memberService = new YouthUnionMemberService();
        private PositionService positionService = new PositionService();

        public YouthUnionMemberController()
            : base()
        {

            ViewBag.BreadCrumb.Add(new BreadcrumbLink() { Link = "/YouthUnionUniversity/YouthUnionMember/", Title = "Đoàn viên" });
        }
        public override void AssignPermission()
        {
            ViewBag.VIEW_MEMBER_OWN_FACULTY = permissions.Contains("VIEW_MEMBER_OWN_FACULTY");
            ViewBag.MANAGE_MEMBER = permissions.Contains("MANAGE_MEMBER");
            ViewBag.VIEW_ALL_MEMBER = permissions.Contains("VIEW_ALL_MEMBER");
            ViewBag.VIEW_MEMBER_OWN_CLASS = permissions.Contains("VIEW_MEMBER_OWN_CLASS");

            ViewBag.MANAGE_STAFF = permissions.Contains("MANAGE_STAFF");
        }
        //
        // GET: /YouthUnionUniversity/YouthUnionMember/
        [AllowPermission(RoleID = "VIEW_MEMBER_OWN_FACULTY|MANAGE_STAFF|VIEW_ALL_MEMBER|VIEW_MEMBER_OWN_CLASS")]
        public ActionResult Index()
        {

            if (!ViewBag.VIEW_ALL_MEMBER)
            {
                if (ViewBag.VIEW_MEMBER_OWN_FACULTY && currentFaculty == null)
                {
                    ViewBag.ErrorMessage = "Bạn chưa có thông tin về Đoàn Viện/Khoa trong hệ thống!";
                    return View();
                }
                if (ViewBag.VIEW_MEMBER_OWN_CLASS && currentClass == null)
                {
                    ViewBag.ErrorMessage = "Bạn chưa có thông tin về Chi đoàn trong hệ thống!";
                    return View();
                }
            }

            List<Item> types = new List<Item>();//loại đoàn viên

            if (ViewBag.VIEW_ALL_MEMBER || ViewBag.VIEW_MEMBER_OWN_FACULTY)
            {
                types.Add(new Item() { ID = ConstraintUnionMemberType.STUDENT, Name = "Sinh viên" });
                types.Add(new Item() { ID = ConstraintUnionMemberType.LECTURE, Name = "Giảng viên" });
                ViewBag.AcademicYearID = new SelectList(academicYearService.GetAll(), "ID", "Name");
                int? facultyID = null;
                if (ViewBag.VIEW_MEMBER_OWN_FACULTY && currentFaculty != null)
                    facultyID = currentFaculty.ID;
                var firstAcademicYear = academicYearService.GetFirst();
                if (firstAcademicYear != null)
                {
                    ViewBag.ClassID = new SelectList(classService.GetByFacultyAndAcademicYear(facultyID, firstAcademicYear.ID, ConstraintUnionClassType.STUDENT), "ID", "Name");
                }
                else
                {
                    ViewBag.ClassID = new SelectList(null);
                }

            }
            else if (ViewBag.VIEW_MEMBER_OWN_CLASS)
            {
                if (currentClass.Type == ConstraintUnionClassType.STUDENT)
                    types.Add(new Item() { ID = ConstraintUnionMemberType.STUDENT, Name = "Sinh viên" });
                else
                    types.Add(new Item() { ID = ConstraintUnionMemberType.LECTURE, Name = "Giảng viên" });

            }

            if (ViewBag.MANAGE_STAFF)
            {
                types.Add(new Item() { ID = ConstraintUnionMemberType.STAFF, Name = "Cán bộ Đoàn trường" });
            }


            if (ViewBag.VIEW_ALL_MEMBER)
            {
                ViewBag.FacultyID = new SelectList(facultyService.GetAll(), "ID", "Name");
            }

            if (types.Count > 1)
                ViewBag.Type = new SelectList(types, "ID", "Name");


            ViewBag.ReligionID = new SelectList(new ReligionService().GetAll(), "ID", "Name");

            return View();
        }

        [HttpPost, ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult Search(SearchMemberViewModel searchForm)
        {
            List<Item> types = new List<Item>();//loại đoàn viên

            if (ViewBag.VIEW_ALL_MEMBER || ViewBag.VIEW_MEMBER_OWN_FACULTY)
            {
                types.Add(new Item() { ID = ConstraintUnionMemberType.STUDENT, Name = "Sinh viên" });
                types.Add(new Item() { ID = ConstraintUnionMemberType.LECTURE, Name = "Giảng viên" });
                ViewBag.AcademicYearID = new SelectList(academicYearService.GetAll(), "ID", "Name", searchForm.AcademicYearID);


                ViewBag.ClassID = new SelectList(classService.GetByFacultyAndAcademicYear(searchForm.FacultyID, null, ConstraintUnionClassType.STUDENT), "ID", "Name", searchForm.ClassID);
            }
            else if (ViewBag.VIEW_MEMBER_OWN_CLASS)
            {
                if (currentClass.Type == ConstraintUnionClassType.STUDENT)
                    types.Add(new Item() { ID = ConstraintUnionMemberType.STUDENT, Name = "Sinh viên" });
                else
                    types.Add(new Item() { ID = ConstraintUnionMemberType.LECTURE, Name = "Giảng viên" });

            }
            if (ViewBag.VIEW_ALL_MEMBER)
            {
                ViewBag.FacultyID = new SelectList(facultyService.GetAll(), "ID", "Name", searchForm.FacultyID);
            }
            if (ViewBag.MANAGE_STAFF)
            {
                types.Add(new Item() { ID = ConstraintUnionMemberType.STAFF, Name = "Cán bộ Đoàn trường" });
            }
            if (types.Count > 1)
                ViewBag.Type = new SelectList(types, "ID", "Name", searchForm.Type);


            ViewBag.ReligionID = new SelectList(new ReligionService().GetAll(), "ID", "Name", searchForm.ReligionID);

            return View(searchForm);
        }


        /// <summary>
        /// Lấy
        /// </summary>
        /// <param search="facultyID"></param>
        /// <param search="academicYearID"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetClassesStudent(long? facultyID, int? academicYearID)
        {

            int classType = ConstraintUnionClassType.STUDENT;
            if (!ViewBag.VIEW_ALL_MEMBER && ViewBag.VIEW_MEMBER_OWN_FACULTY)
            {
                facultyID = currentFaculty.ID;
            }

            return Json(new YouthUnionClassService().GetByFacultyAndAcademicYear(facultyID, academicYearID, classType)
                                                        .Select(x => new { x.ID, x.Name }), JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult GetMembers(int? page, SearchMemberViewModel searchData)
        {

            if (searchData.Type == null)//nếu k có select type
            {
                if (ViewBag.VIEW_ALL_MEMBER || ViewBag.VIEW_MEMBER_OWN_FACULTY)
                    searchData.Type = ConstraintUnionMemberType.STUDENT; // khi load lần đầu cho sv
                else if (ViewBag.VIEW_MEMBER_OWN_CLASS)
                    searchData.Type = currentClass.Type == ConstraintUnionClassType.LECTURE ? ConstraintUnionMemberType.LECTURE : ConstraintUnionMemberType.STUDENT;
                else if (ViewBag.MANAGE_STAFF)
                    searchData.Type = ConstraintUnionMemberType.STAFF;
            }
            //nếu k co select academicyear
            if (searchData.AcademicYearID == null && searchData.Type == ConstraintUnionMemberType.STUDENT)
            {
                if (currentClass != null && currentClass.Type == ConstraintUnionClassType.STUDENT)
                    searchData.AcademicYearID = currentClass.AcademicYearID;
                else
                {
                    var firstAcademicYear = academicYearService.GetFirst();
                    if (firstAcademicYear != null)
                    {
                        searchData.AcademicYearID = firstAcademicYear.ID;
                    }
                }
            }
            if (searchData.ClassID == null && !ViewBag.VIEW_ALL_MEMBER && !ViewBag.VIEW_MEMBER_OWN_FACULTY && ViewBag.VIEW_MEMBER_OWN_CLASS && currentClass != null)
            {
                searchData.ClassID = currentClass.ID;
                searchData.FacultyID = currentFaculty.ID;
            }
            if (searchData.FacultyID == null && !ViewBag.VIEW_ALL_MEMBER && ViewBag.VIEW_MEMBER_OWN_FACULTY && currentFaculty != null)
            {
                searchData.FacultyID = currentFaculty.ID;
            }
            int pageSize = 12;
            int pageNumber = (page ?? 1);


            var model = memberService.FindBySearchViewModel(searchData);
            ViewBag.CountResult = model.Count;
            ViewBag.SearchData = searchData;
            return PartialView("_MembersListPartial", model.ToPagedList(pageNumber, pageSize));
        }

        //Load Dropdownlist Create
        private void LoadCreateDropDownList(long? facultyID, long? classID, int? type, int? academicYearID,
            int? positionUniversityID, int? positionFacultyID, int? positionClassID,
            int raceID = 1, int religionID = 1, int day = 1, int month = 1, int year = 1997)
        {
            List<Item> types = new List<Item>();
            //LOAD kiểu đoàn viên
            if (ViewBag.VIEW_ALL_MEMBER || ViewBag.VIEW_MEMBER_OWN_FACULTY)
            {

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/YouthUnionMember/Details.cshtml
@{
    ViewBag.Title = "Chi tiết Đoàn viên " + ViewBag.Fullname;
    //ViewBag.NoPanel = true;
}

@section styles{
    <link href="~/Assets/addition/css/profile.css" rel="stylesheet" />
}

@if (ViewBag.ErrorMessage != null)
{
    <h3 class="error-message">@ViewBag.ErrorMessage</h3>
}
else
{
    Html.RenderAction("GetProfile", "YouthUnionMember", new { @id = ViewBag.ID });

    <p>
        @Html.ActionLink("Sửa", "Edit", new { id = ViewBag.ID }) |
        @Html.ActionLink("Trở về", "Index")
    </p>
}

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/YouthUnionMember/Import.cshtml
@{
    ViewBag.Title = "Nhập dữ liệu Đoàn viên";
}

@section styles{
    <style>
        .form-group {
            padding-left: 5px !important;
            padding-right: 5px !important;
        }
    </style>
}

@section scripts{
    <script src="~/Assets/addition/js/my-upload.js"></script>
    <script type="text/javascript">

        function onLoading() {
            $('div#divResult').html('');
            $('#btn-import i').show();
            $('#btn-import').attr("disabled", true);
            //cảnh báo khi đòng tab
            $(window).on('beforeunload', function () {
                return '';
            });

        }
        function endLoading() {
            $('#btn-import i').hide();
            $('#btn-import').attr("disabled", false);
            $(window).off('beforeunload');
        }
        window.addEventListener("submit", function (e) {
            //alert($('input[name="file"]').val());
            if ($('input[name="file"]').val() == '') {
                notifyError("Chưa có tệp!");
                return;
            }
            onLoading();
            var error = getErrorUploadFile('input[name="file"]');
            if (error != '') {
                notifyError(error);
                return;
            }
            //console.log($()[0].files[0].name); return;
            //notifyLoading("Đang xử lý...");

            var form = e.target;
            if (form.getAttribute("enctype") === "multipart/form-data") {
                if (form.dataset.ajax) {
                    e.preventDefault();
                    e.stopImmediatePropagation();
                    var xhr = new XMLHttpRequest();
                    xhr.open(form.method, form.action);
                    xhr.onreadystatechange = function () {
                        if (xhr.readyState == 4 && xhr.status == 200) {
                            if (form.dataset.ajaxUpdate) {
                                var updateTarget = document.querySelector(form.dataset.ajaxUpdate);
                                if (updateTarget) {
                                    updateTarget.innerHTML = xhr.responseText;
                                    endLoading();
                                    notifySuccess("Thao tác thành công! Bạn hãy xem kết quả!")
                                }
                            }
                        } else {
                            notifyError("Đã xảy ra lỗi!");
                            endLoading();
                        }
                    };
                    xhr.send(new FormData(form));
                }
            }
        }, true);

        $(function () {
            //uplòad
            $('input[type="file"]').change(function () {
                var error = getErrorUploadFile('input[type="file"]');
                if (error != '') {
                    notifyError(error);
                    $(this).val('');
                }
                $('#txtFile').val($(this).val());
            });
        });
    </script>
}
<div class="box-tool">
    <div class="row">
        <div class="col-md-6 col-sm-12 col-xs-12">
            @using (Ajax.BeginForm("GetResultImport", null,
    new AjaxOptions()
    {
        HttpMethod = "POST",
        OnBegin = "onLoading()",
        OnSuccess = "endLoading()",
        UpdateTargetId = "divResult",
        InsertionMode = InsertionMode.Replace
    },
        new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-md-3">Loại đoàn viên:</label>
                        <div class="col-md-4">
                            @Html.DropDownList("Type", null, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Khóa:</label>
                        <div class="col-md-3">
                            @Html.DropDownList("AcademicYearID", null, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">Tùy chọn:</label>
                        <div class="col-md-8">
                            @Html.DropDownList("Option", null, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3">Tệp Excel:</label>
                        <div class="col-md-8">
                            <div class="input-group">
                                <input name="txtFile" placeholder="Chọn tệp .xls, .xlsx" type="text" readonly="readonly" id="txtFile" class="form-control">
                                <span class="group-span-filestyle input-group-btn">
                                    <button id="btnBrowse" type="button" value="Chọn tệp" class="btn btn-primary" style="padding:6px 12px !important; border-radius: 0"
                                            onclick="document.getElementById('fileUpload').click();">
                                        <i class="fa fa-folder-open"></i>
                                    </button>
                                </span>

                            </div>

                            <input type="file" style="display:none" accept=".xls, .xlsx" name="file" id="fileUpload" />

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <button id="btn-import" class="btn btn-success" type="submit">
                                <i style="display:none; margin-right:5px" class="fa fa-circle-o-notch fa-spin"></i> Tải lên
                            </button>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="col-md-6 col-xs-12 col-sm-12" id="instruction">
            <h3> Yêu cầu đối với tệp:</h3>
            <ul>
                <li>Là tệp Excel (*.xls, *.xlsx).</li>
                <li>Hàng đầu tiên là tên các cột</li>
                <li>Các cột cần có: [MÃ SINH VIÊN], [HỌ], [TÊN], [NGÀY SINH], [GIỚI TÍNH], [LỚP], [KHOA]. </li>
                <li>Tên cột không phân biệt hoa thường.</li>
                <li>Tệp mẫu tải xuống tại <a target="_blank" href="https://drive.google.com/file/d/12GkIPXpCFbqr2Ntu-yvfb2C8W-HKMp_j/view?usp=sharing">đây</a>.</li>
            </ul>
        </div>
    </div>
</div>
<div id="divResult">
    
    <!-- Bảng trả về ở đây -->
</div>

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/YouthUnionMember/Index.cshtml
@using QLDoanTruong.Common;

@model QLDoanTruong.Model.ViewModel.SearchMemberViewModel

@{
    ViewBag.Title = "Quản lý Đoàn viên";

}
@section styles{
    <style>
        .col-fix {
            padding-left: 1px;
            padding-right: 0px;
        }

        .row-fix {
            margin-bottom: 2px;
        }
    </style>
}
@section scripts{
    <script>
        function hideClass() {
            if ($('#Type').val() != '@QLDoanTruong.Common.ConstraintUnionMemberType.STUDENT')

                $('#Type').trigger("change");

        }
        $(document).ready(function () {
            //confirm

            $('#UnionMemberArea').on('click', "a.btn-delete", function (e) {

                var tr = $('tr', 'table').get($(this).closest('tr').index());
                confirmDelete('@Url.Action("Delete")', { id: $(this).data('id') },
                    function () { $(tr).remove(); });
                e.preventDefault();
            });



            $('a#btn-add').click(function (e) {
                e.preventDefault();
                var url = $(this).attr('href');
                var params = [];

                if ($('#FacultyID').val() != '' && $('#FacultyID').val() != undefined)
                    params.push('facultyID=' + $('#FacultyID').val());
                if ($('#Type').val() != '' && $('#Type').val() != undefined)
                    params.push('type=' + $('#Type').val());
                if ($('#ClassID').val() != '' && $('#ClassID').val() != undefined)
                    params.push('classID=' + $('#ClassID').val());
                if ($('#AcademicYearID').val() != '' && $('#AcademicYearID').val() != undefined)
                    params.push('academicYearID=' + $('#AcademicYearID').val());
                var par = params.join('&');
                if (par != '')
                    url += '?' + par;
                window.location.href = url;
            });
            //toogle with type
            $('#Type').change(function () {
                if ($(this).val() == '@ConstraintUnionMemberType.STAFF') {
                    $('#unit').hide();
                    $('#class').hide();

                }
                else if ($(this).val() == '@ConstraintUnionMemberType.LECTURE') {
                    $('#unit').show();
                    $('#academic').hide();
                    $('#class').hide();

                }
                else {
                    $('#unit').show();
                    $('#academic').show();
                    $('#class').show();

                }

            });
            //load class
            $('#Type, #FacultyID, #AcademicYearID').change(function () {
                $('#ClassID').children('option:not(:first)').remove();

                $.post("@Url.Action("GetClassesStudent")",
                    {
                        memberType: $('#Type').val(),
                        facultyID: $('#FacultyID').val(),
                        academicYearID: $('#AcademicYearID').val()
                    },
                    function (result) {
                        //console.log(result);
                        $.each(result, function (index, item) {
                            $('#ClassID').append($('<option>', {
                                value: item.ID,
                                text: item.Name
                            }));
                        });

                    }, 'json');
            });

            hideClass();

        });
    </script>
}

@if (ViewBag.ErrorMessage != null)
{
    <h3 class="error-message">@ViewBag.ErrorMessage</h3>
}
else
{
    
        <div class="box-tool">
            <div class="form-horizontal">
                <div class="col-md-@((ViewBag.MANAGE_MEMBER || ViewBag.MANAGE_STAFF)?"10":"12")">
                    @using (Html.BeginForm("Index", "YouthUnionMember", FormMethod.Post))
                    {

                        @Html.AntiForgeryToken()

                        <div class="row row-fix">
                            @if (ViewBag.Type != null)
                            {
                                <div class="col-md-3 col-fix">
                                    @Html.DropDownList("Type", null, new { @class = "form-control" })
                                </div>
                            }

                            <div id="unit">
                                @if (ViewBag.FacultyID != null)
                                {
                                    <div class="col-md-4 col-fix">
                                        @Html.DropDownList("FacultyID", null, "--- Chọn Liên Chi đoàn ---", new { @class = "form-control" })
                                    </div>
                                }
                                @if (ViewBag.AcademicYearID != null)
                                {
                                    <div class="col-md-1 col-fix" id="academic">
                                        @Html.DropDownList("AcademicYearID", null, new { @class = "form-control" })
                                    </div>
                                }
                            </div>
                            @if (ViewBag.ClassID != null)
                            {
                                <div class="col-md-4 col-fix" id="class">
                                    @Html.DropDownList("ClassID", null, "--- Chọn chi đoàn ---", new { @class = "form-control" })
                                </div>
                            }
                        </div>

                        <div class="row row-fix">
                            <div class="col-md-3 col-fix">
                                @Html.DropDownList("ReligionID", null, "--- Chọn tôn giáo ---", new { @class = "form-control" })
                            </div>
                            <div class="col-md-3 col-fix">
                                @Html.TextBoxFor(m => m.MemberCode, new { @class = "form-control", @placeholder = "Mã SV/CB" })
                            </div>
                            <div class="col-md-3 col-fix">
                                @Html.TextBoxFor(m => m.Fullname, new { @class = "form-control", @placeholder = "Họ tên" })

                            </div>
                            <div class="col-md-3 col-fix">
                                @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", @placeholder = "Số điện thoại" })
                            </div>
                        </div>
                        <div class="pull-right">
                            <button type="submit" class="btn btn-success"> <i class="fa fa-search"></i> Tìm kiếm </button>
                            <button type="submit" formaction="@Url.Action("ExportExcel")" class="btn btn-default">
                                <i class="fa fa-file-excel-o"></i> Xuất Excel
                            </button>
                        </div>
                    }
                </div>
                @if (ViewBag.MANAGE_MEMBER || ViewBag.MANAGE_STAFF)
                {
                    <div class="col-md-2">

                        <div class="row row-fix">
                            <a href="@Url.Action("Create")" class="btn btn-primary col-md-12" id="btn-add"> <i class="fa fa-plus"></i> Thêm Đoàn viên</a>
                        </div>
                        @if (ViewBag.VIEW_ALL_MEMBER)
                        {
                            <div class="row row-fix">
                                <a href="@Url.Action("Import")" class="btn btn-warning col-md-12"> <i class="fa fa-upload"></i> Nhập dữ liệu</a>
                            </div>
                        }
                    </div>
                }

            </div>

        </div>
        <div class="clearfix"></div>
        <div id="UnionMemberArea">
            @{Html.RenderAction("GetMembers", "YouthUnionMember", new { page = 1 });}
        </div>
}

QLDoanTruong.Web/Areas/YouthUnionUniversity/Views/YouthUnionMember/_ImportMemberPartial.cshtml
@model IEnumerable<QLDoanTruong.Model.ViewModel.ImportMemberViewModel>

@if (ViewBag.ErrorMessage != null)
{
    <h3 class="error-message">@ViewBag.ErrorMessage</h3>
}
else
{
    <p>
        <b>Kết quả: </b>
        <span style="color:green; margin-left:20px"> <i class="fa fa-check"></i> Thành công: @ViewBag.NumberSuccess </span>
        <span style="color: red; margin-left: 20px"><i class="fa fa-close"></i> Lỗi: @ViewBag.NumberFail</span>
    </p>

    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Mã sinh viên</th>
            <th>Họ</th>
            <th>Tên</th>
            <th>Ngày sinh</th>
            <th>Giới tính</th>
            <th>Lớp</th>
            <th>Khoa</th>
            <th>Kết quả</th>
        </tr>
        @{int stt = 1;}
        @foreach (var item in Model)
        {
            <tr>
                <td>@(stt++)</td>
                <td>@item.StudentCode</td>
                <td>@item.LastName</td>
                <td>@item.FirstName</td>
                <td>@item.DateOfBirth</td>
                <td>@item.Gender</td>
                <td>@item.Class</td>
                <td>@item.Faculty</td>
                <td>
                    @if (item.IsSuccess)
                    {
                        <span style="color:green; font-weight:bold"><i class="fa fa-check"></i> Thành công: </span>@item.Message
                    }
                    else
                    {
                        <span style="color:red; font-weight:bold"> <i class="fa fa-close"></i> Lỗi: </span>@item.Message
                    }
                </td>
            </tr>
        }
    </table>

}